//%GenSrc:1:OWjeF04ylkiDo1x+raOSJg
//%CodeKey:BqyNKSE/FEmzT2n/jSltHg
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Agent.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    public partial class Agent : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            float f1 = 0.0f;
            float f2 = 0.0f;
            int n0c = -1;
            int n12c = -1;
            int n13c = -1;
            int n14c = -1;
            int n18_1i = 0;
            int n19c = -1;
            int n1c = -1;
            int n20c = -1;
            int n21c = -1;
            int n22c = -1;
            int n23c = -1;
            int n2c = -1;
            int n4c = -1;
            int n5c = -1;
            int n6c = -1;
            NodeVal n1_1r = NodeVal.Invalid;
            NodeVal n13_1r = NodeVal.Invalid;
            NodeVal n14_1r = NodeVal.Invalid;
            NodeVal n19_1r = NodeVal.Invalid;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n20_1r = NodeVal.Invalid;
            NodeVal n21_1r = NodeVal.Invalid;
            NodeVal n22_1r = NodeVal.Invalid;
            NodeVal n23_1r = NodeVal.Invalid;
            NodeVal n5_1r = NodeVal.Invalid;
            NodeVal n6_1r = NodeVal.Invalid;
            Vector3 v1 = Vector3.zero;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        break;
                    case 49:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        if(ret != NodeVal.Success) {
                            if (++n0c > 2) {
                                n0c = 1;
                                node = 0;
                                yield return null;
                            } else {
                                node = n0c;
                            }
                        } else {
                            n0c = 1;
                            node = 0;
                            yield return null;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, true, false);
                        #endif
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 3;
                        node = 3;
                        n1_1r = NodeVal.Success;
                        break;
                    case 50:

                        n1_1r = (NodeVal)System.Math.Max((int)n1_1r, (int)ret);
                        if (ret == NodeVal.Success && n1c < 4) {
                            node = ++n1c;
                        } else {
                            n1c = 3;
                            node = 49;
                            ret = n1_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 11;
                        node = 11;
                        n2_1r = NodeVal.Success;
                        break;
                    case 51:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 12) {
                            node = ++n2c;
                        } else {
                            n2c = 11;
                            node = 49;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        ret = (!this.isActive)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif
                        node = 50;
                        break;
                    case 4:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n4c = 5;
                        node = 5;
                        break;
                    case 53:

                        if(ret != NodeVal.Success) {
                            if (++n4c > 6) {
                                n4c = 5;
                                node = 50;
                            } else {
                                node = n4c;
                            }
                        } else {
                            n4c = 5;
                            node = 50;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 5:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n5c = 7;
                        node = 7;
                        n5_1r = NodeVal.Success;
                        break;
                    case 54:

                        n5_1r = (NodeVal)System.Math.Max((int)n5_1r, (int)ret);
                        if (ret == NodeVal.Success && n5c < 8) {
                            node = ++n5c;
                        } else {
                            n5c = 7;
                            node = 53;
                            ret = n5_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 6:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n6c = 9;
                        node = 9;
                        n6_1r = NodeVal.Success;
                        break;
                    case 55:

                        n6_1r = (NodeVal)System.Math.Max((int)n6_1r, (int)ret);
                        if (ret == NodeVal.Success && n6c < 10) {
                            node = ++n6c;
                        } else {
                            n6c = 9;
                            node = 53;
                            ret = n6_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 7:

                        ret = (this.isTop)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif
                        node = 54;
                        break;
                    case 8:


                            v1 = this.NonActiveDestination();
                            transform.position = Vector3.MoveTowards(transform.position, v1, 1f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                        node = 54;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 9:

                        ret = (!this.isTop)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif
                        node = 55;
                        break;
                    case 10:


                            v1 = this.NonActiveDestination();
                            transform.position = Vector3.MoveTowards(transform.position, v1, 1f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                        node = 55;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(51, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 11:

                        ret = (this.isActive)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, ret, false, false);
                        #endif
                        node = 51;
                        break;
                    case 12:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(47, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n12c = 13;
                        node = 13;
                        break;
                    case 61:

                        if(ret != NodeVal.Success) {
                            if (++n12c > 14) {
                                n12c = 13;
                                node = 51;
                            } else {
                                node = n12c;
                            }
                        } else {
                            n12c = 13;
                            node = 51;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(47, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 13:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(45, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n13c = 15;
                        node = 15;
                        n13_1r = NodeVal.Success;
                        break;
                    case 62:

                        n13_1r = (NodeVal)System.Math.Max((int)n13_1r, (int)ret);
                        if (ret == NodeVal.Success && n13c < 16) {
                            node = ++n13c;
                        } else {
                            n13c = 15;
                            node = 61;
                            ret = n13_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(45, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 14:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(49, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n14c = 17;
                        node = 17;
                        n14_1r = NodeVal.Success;
                        break;
                    case 63:

                        n14_1r = (NodeVal)System.Math.Max((int)n14_1r, (int)ret);
                        if (ret == NodeVal.Success && n14c < 18) {
                            node = ++n14c;
                        } else {
                            n14c = 17;
                            node = 61;
                            ret = n14_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(49, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 15:

                        ret = (this.CheckIfGoHome())? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(52, _liveHandle, ret, false, false);
                        #endif
                        node = 62;
                        break;
                    case 16:


                        do
                        {
                            ret = (this.SetTargetToLeave());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(46, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 62;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(46, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 17:

                        ret = (!this.CheckIfGoHome())? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(50, _liveHandle, ret, false, false);
                        #endif
                        node = 63;
                        break;
                    case 18:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(48, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n18_1i = 0;
                        node = EvalUtility(ref n18_1i);
                        break;
                    case 67:

                        if (!(ret == NodeVal.Success || ret == NodeVal.Running) && n18_1i != 31) {
                            node = EvalUtility(ref n18_1i);
                            break;
                        }
                        node = 63;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(48, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 19:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n19c = 24;
                        node = 24;
                        n19_1r = NodeVal.Success;
                        break;
                    case 68:

                        n19_1r = (NodeVal)System.Math.Max((int)n19_1r, (int)ret);
                        if (ret == NodeVal.Success && n19c < 28) {
                            node = ++n19c;
                        } else {
                            n19c = 24;
                            node = 67;
                            ret = n19_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 20:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n20c = 29;
                        node = 29;
                        n20_1r = NodeVal.Success;
                        break;
                    case 69:

                        n20_1r = (NodeVal)System.Math.Max((int)n20_1r, (int)ret);
                        if (ret == NodeVal.Success && n20c < 33) {
                            node = ++n20c;
                        } else {
                            n20c = 29;
                            node = 67;
                            ret = n20_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 21:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n21c = 34;
                        node = 34;
                        n21_1r = NodeVal.Success;
                        break;
                    case 70:

                        n21_1r = (NodeVal)System.Math.Max((int)n21_1r, (int)ret);
                        if (ret == NodeVal.Success && n21c < 38) {
                            node = ++n21c;
                        } else {
                            n21c = 34;
                            node = 67;
                            ret = n21_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 22:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n22c = 39;
                        node = 39;
                        n22_1r = NodeVal.Success;
                        break;
                    case 71:

                        n22_1r = (NodeVal)System.Math.Max((int)n22_1r, (int)ret);
                        if (ret == NodeVal.Success && n22c < 43) {
                            node = ++n22c;
                        } else {
                            n22c = 39;
                            node = 67;
                            ret = n22_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 23:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(36, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n23c = 44;
                        node = 44;
                        n23_1r = NodeVal.Success;
                        break;
                    case 72:

                        n23_1r = (NodeVal)System.Math.Max((int)n23_1r, (int)ret);
                        if (ret == NodeVal.Success && n23c < 48) {
                            node = ++n23c;
                        } else {
                            n23c = 44;
                            node = 67;
                            ret = n23_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(36, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 24:


                        ret = (this.SetTargetToPP());
                        node = 68;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(56, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 25:

                        ret = ((transform.position - (this.PP).transform.position).sqrMagnitude <= (2.25f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(55, _liveHandle, ret, false, false);
                        #endif
                        node = 68;
                        break;
                    case 26:


                        do
                        {
                            ret = (this.SetTargetToStay());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(54, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 68;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(54, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 27:


                        f1 = Time.time;
                        f2 = UnityEngine.Random.Range(1f, 3f);

                        do
                        {
                                ret = ((Time.time - f1) > f2)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {
                                if (this.scared) {
                                    node = 2;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(53, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 68;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(53, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 28:


                        do
                        {
                            ret = (this.TakeCandyFromPP());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(77, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 68;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(77, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 29:


                        ret = (this.SetTargetToBB());
                        node = 69;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(61, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 30:

                        ret = ((transform.position - (this.BB).transform.position).sqrMagnitude <= (2.25f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(60, _liveHandle, ret, false, false);
                        #endif
                        node = 69;
                        break;
                    case 31:


                        do
                        {
                            ret = (this.SetTargetToStay());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(59, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 69;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(59, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 32:


                        f1 = Time.time;
                        f2 = UnityEngine.Random.Range(1f, 3f);

                        do
                        {
                                ret = ((Time.time - f1) > f2)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {
                                if (this.scared) {
                                    node = 2;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(58, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 69;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(58, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 33:


                        do
                        {
                            ret = (this.TakeCandyFromBB());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(57, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 69;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(57, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 34:


                        ret = (this.SetTargetToHS());
                        node = 70;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(65, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 35:

                        ret = ((transform.position - (this.HS).transform.position).sqrMagnitude <= (2.25f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(64, _liveHandle, ret, false, false);
                        #endif
                        node = 70;
                        break;
                    case 36:


                        do
                        {
                            ret = (this.SetTargetToStay());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(63, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 70;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(63, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 37:


                        f1 = Time.time;
                        f2 = UnityEngine.Random.Range(1f, 3f);

                        do
                        {
                                ret = ((Time.time - f1) > f2)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {
                                if (this.scared) {
                                    node = 2;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(62, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 70;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(62, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 38:


                        do
                        {
                            ret = (this.TakeCandyFromHS());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(66, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 70;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(66, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 39:


                        do
                        {
                            ret = (this.SetTargetToSP());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(72, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 71;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(72, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 40:

                        ret = ((transform.position - (this.SP).transform.position).sqrMagnitude <= (2.25f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(73, _liveHandle, ret, false, false);
                        #endif
                        node = 71;
                        break;
                    case 41:


                        do
                        {
                            ret = (this.SetTargetToStay());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(74, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 71;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(74, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 42:


                        f1 = Time.time;
                        f2 = UnityEngine.Random.Range(1f, 3f);

                        do
                        {
                                ret = ((Time.time - f1) > f2)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {
                                if (this.scared) {
                                    node = 2;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(75, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 71;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(75, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 43:


                        do
                        {
                            ret = (this.TakeCandyFromSP());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(76, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 71;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(76, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 44:


                        ret = (this.SetTargetToRW());
                        node = 72;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(67, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 45:

                        ret = ((transform.position - (this.RW).transform.position).sqrMagnitude <= (2.25f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(68, _liveHandle, ret, false, false);
                        #endif
                        node = 72;
                        break;
                    case 46:


                        do
                        {
                            ret = (this.SetTargetToStay());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(69, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 72;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(69, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 47:


                        f1 = Time.time;
                        f2 = UnityEngine.Random.Range(1f, 3f);

                        do
                        {
                                ret = ((Time.time - f1) > f2)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {
                                if (this.scared) {
                                    node = 2;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(70, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 72;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(70, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 48:


                        do
                        {
                            ret = (this.TakeCandyFromRW());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(71, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 72;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(71, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "OWjeF04ylkiDo1x+raOSJg") {
                _live = live;
                codeMatch = (codeKey == "BqyNKSE/FEmzT2n/jSltHg");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

        public int EvalUtility(ref int filter)
        {
            float f1 = float.MinValue;
            float f2 = 0.0f;
            int i1 = 19;
            int i2 = 0;

            /* Pitpats => Go To Pitpats */
            f2 = (1f - Mathf.Max(0f, Mathf.Min(1f, (this.WantForPitPats()) / 105f)));
            if ((filter & 1) == 0)
            {
                if (f2 > f1) {
                    f1 = f2; i1 = 19;
                #if UNITY_EDITOR
                                if (_live == null && f1 == 1f) { filter |= 1; return i1; }
                #else
                    if (f1 == 1f) { filter |= 1; return i1; }
                #endif
                i2 = 1;
                }
            }

            /* Booster Bars => Go To BB */
            f2 = (1f - Mathf.Max(0f, Mathf.Min(1f, (this.WantForBoosterBars()) / 105f)));
            if ((filter & 2) == 0)
            {
                if (f2 > f1) {
                    f1 = f2; i1 = 20;
                #if UNITY_EDITOR
                                if (_live == null && f1 == 1f) { filter |= 2; return i1; }
                #else
                    if (f1 == 1f) { filter |= 2; return i1; }
                #endif
                i2 = 2;
                }
            }

            /* HS => Go to HS */
            f2 = (1f - Mathf.Max(0f, Mathf.Min(1f, (this.WantForHerShe()) / 105f)));
            if ((filter & 4) == 0)
            {
                if (f2 > f1) {
                    f1 = f2; i1 = 21;
                #if UNITY_EDITOR
                                if (_live == null && f1 == 1f) { filter |= 4; return i1; }
                #else
                    if (f1 == 1f) { filter |= 4; return i1; }
                #endif
                i2 = 4;
                }
            }

            /* RW => Go to RW */
            f2 = (1f - Mathf.Max(0f, Mathf.Min(1f, (this.WantForRedAndWhites()) / 105f)));
            if ((filter & 8) == 0)
            {
                if (f2 > f1) {
                    f1 = f2; i1 = 22;
                #if UNITY_EDITOR
                                if (_live == null && f1 == 1f) { filter |= 8; return i1; }
                #else
                    if (f1 == 1f) { filter |= 8; return i1; }
                #endif
                i2 = 8;
                }
            }

            /* SP => Go to SP */
            f2 = (1f - Mathf.Max(0f, Mathf.Min(1f, (this.WantForSmallPleasers()) / 105f)));
            if ((filter & 16) == 0)
            {
                if (f2 > f1) {
                    f1 = f2; i1 = 23;
                #if UNITY_EDITOR
                                if (_live == null && f1 == 1f) { filter |= 16; return i1; }
                #else
                    if (f1 == 1f) { filter |= 16; return i1; }
                #endif
                i2 = 16;
                }
            }
            filter |= i2;
            return i1;
        }
    }
}
